project:
  type: website

website:
  title: "<span style=font-size:x-large>Gonzalo Talavera Forlin</span><br><span style=font-size:small>Visualización de datos para politicas públicas</span>"
  navbar:
    background: "#5297AC"
    fixed: true
    search: true
    logo: "/images/gtf_headshot.jpeg"
    left:
      - href: about.qmd  # Added "Gonzalo" navigation item
        text: Bio
      - href: servicios.qmd  # Added "Servicios" navigation item
        text: Servicios
      - href: portafolio.qmd  # Added "Proyectos" navigation item
        text: Portafolio
    tools:
      - icon: twitter
        href: https://twitter.com/gonzalotalavera
      - icon: github
        href: https://github.com/gtalavera
      - icon: linkedin
        href: https://www.linkedin.com/in/gonzalotalavera/
  page-footer: "Esta web fue hecha por mi, usando quarto. 2023" 
  google-analytics: "G-Z7H5N2FX19"

format:
  html:
    page-layout: full
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

editor: visual

